
name: Publish packages to NPM Package Registry

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          scope: "@neobeach"

      - name: Check if @neobeach/modules-graylog version has been updated
        id: graylog
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: graylog/package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @neobeach/modules-graylog
        if: steps.graylog.outputs.changed == 'true'
        run: npm publish graylog --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check if @neobeach/modules-sendgrid version has been updated
        id: sendgrid
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: sendgrid/package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @neobeach/modules-sendgrid
        if: steps.sendgrid.outputs.changed == 'true'
        run: npm publish sendgrid --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
